using System;

namespace HotelManagement.Shared
{
    public static class ReportLogger
    {
        public static void LogReportGenerated(string reportType, string user, DateTime? startDate = null, DateTime? endDate = null)
        {
            string dateRangeStr = (startDate.HasValue && endDate.HasValue) 
                ? $" from {startDate.Value.ToShortDateString()} to {endDate.Value.ToShortDateString()}" 
                : " (All time)";
            Logger.LogInfo($"[REPORT] {reportType} generated by User: {user}{dateRangeStr}");
        }

        public static void LogReportExported(string reportType, string format, string user)
        {
            Logger.LogInfo($"[REPORT] {reportType} exported to {format} by User: {user}");
        }
        
        public static void LogDashboardAccessed(string user)
        {
            Logger.LogInfo($"[DASHBOARD] Admin dashboard accessed by User: {user}");
        }
    }
}
